"""Per-request stem deliverable sink.

`OutputSink` writes a small, fixed set of audio artifacts (currently the
isolated drum mix and the drumless mix) into `<settings.outputs_dir>/<id>/`
as FLAC, and exposes URL paths that the FastAPI app serves via a
`StaticFiles` mount.

Unlike `DebugSink`, this sink:
  - is always created for every /transcribe and /transcribe/resume call
    (the operator-facing stems are part of the API contract, not a
    debug aid),
  - emits only FLAC (lossless + compact enough to embed in HTTP responses
    via URL without burning user bandwidth),
  - is the source of truth for the stem URLs returned in the response.

Resume requests reuse the original debug folder's name as the outputs
folder name, so a resume that skips stems_all still surfaces the URLs
generated by the original fresh /transcribe run (if those FLACs still
live under `<outputs_dir>/<name>/`).
"""
from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import soundfile as sf

log = logging.getLogger(__name__)


# Public route prefix served by the FastAPI app via `StaticFiles`. Bare
# string (no leading host) because the caller composes it against its
# configured transcriber base URL (e.g. `/api` in dev, `https://...` in
# prod). Leading slash so concatenation with a non-slashed base yields a
# valid path either way.
ROUTE_PREFIX = "/outputs"


# Lossless, modest-size encoding. `PCM_16` is fine because Demucs's wav
# outputs are already int16; we read them as float32 just to do the
# bass+other+vocals sum without integer overflow, then quantise back.
FLAC_SUBTYPE = "PCM_16"


class OutputSink:
    """Writes per-request stem deliverables and tracks their URL paths.

    Construction takes the request's folder name (same convention as
    `DebugSink` — see `debug.mint_request_folder_name`) so an operator can
    correlate `/outputs/<name>/` with `/debug/<name>/`.
    """

    def __init__(self, base_dir: Path, folder_name: str) -> None:
        self.base_dir = base_dir
        self.folder_name = folder_name
        self.dir = base_dir / folder_name
        self.dir.mkdir(parents=True, exist_ok=True)

    # ----------------------------------------------------------- writes

    def save_flac_from_wav(self, name: str, src: Path) -> Path | None:
        """Re-encode `src` (any libsndfile-readable format) into `<dir>/<name>.flac`.

        Returns the destination path on success, or `None` on failure
        (logged, not raised — a missing deliverable is recoverable from
        the corresponding debug artifact if the operator needs to).
        """
        if not src.exists():
            log.warning("OutputSink: source %s does not exist; skipping %s", src, name)
            return None
        dest = self.dir / f"{name}.flac"
        try:
            data, sr = sf.read(str(src), always_2d=True, dtype="float32")
            np.clip(data, -1.0, 1.0, out=data)
            sf.write(str(dest), data, sr, format="FLAC", subtype=FLAC_SUBTYPE)
        except (OSError, RuntimeError, ValueError) as exc:
            log.warning("OutputSink: encoding %s -> %s failed: %s", src, dest, exc)
            return None
        return dest

    # -------------------------------------------------------------- read

    def existing_path(self, name: str) -> Path | None:
        """Return `<dir>/<name>.flac` if it already exists on disk."""
        candidate = self.dir / f"{name}.flac"
        return candidate if candidate.is_file() else None

    def url_for(self, name: str) -> str:
        """URL path (no host) for a stem deliverable by base name."""
        return f"{ROUTE_PREFIX}/{self.folder_name}/{name}.flac"


def make_output_sink(folder_name: str, base_dir: Path) -> OutputSink | None:
    """Construct an OutputSink rooted at `base_dir / folder_name`, or
    return `None` if the base directory can't be created.

    Falls back to None rather than raising so a misconfigured volume mount
    degrades to "no URLs in the response" rather than failing the whole
    transcription request.
    """
    try:
        base_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        log.warning("Could not create outputs dir %s: %s", base_dir, exc)
        return None
    try:
        return OutputSink(base_dir, folder_name)
    except OSError as exc:
        log.warning("Could not create outputs request dir %s/%s: %s", base_dir, folder_name, exc)
        return None
