"""Per-request stem deliverable sink.

`OutputSink` writes a small, fixed set of audio artifacts (the isolated
drum mix and the drumless mix from `stems_all`, plus the per-instrument
stems from `stems_per`) into `<settings.outputs_dir>/<id>/` as FLAC, and
exposes URL paths that the FastAPI app serves via a `StaticFiles` mount.

Each artifact is written the instant its producing stage finishes, not
at the end of the request, so deliverables are downloadable while the
slow LLM stages are still running. The request directory is created
lazily on the first successful write, so an `outputs/<id>/` folder that
exists at all is guaranteed to be non-empty.

Unlike `DebugSink`, this sink:
  - is always created for every /transcribe and /transcribe/resume call
    (the operator-facing stems are part of the API contract, not a
    debug aid),
  - emits only FLAC (lossless + compact enough to embed in HTTP responses
    via URL without burning user bandwidth),
  - is the source of truth for the stem URLs returned in the response.

Resume requests reuse the original debug folder's name as the outputs
folder name, so a resume that skips stems_all still surfaces the URLs
generated by the original fresh /transcribe run (if those FLACs still
live under `<outputs_dir>/<name>/`).
"""
from __future__ import annotations

import logging
import subprocess
from pathlib import Path

import numpy as np
import soundfile as sf

log = logging.getLogger(__name__)


# MP3 bitrate for the debug-zip audio tracks. 128 kbps is the
# bandwidth/quality sweet spot for drum stems: high enough that transients
# survive intact, low enough that an N-stem debug bundle for a 3-minute song
# stays well under 25 MB. Bump if listenable accuracy of the per-stem audio
# starts mattering more than the bundle size.
MP3_BITRATE = "128k"


# Public route prefix served by the FastAPI app via `StaticFiles`. Bare
# string (no leading host) because the caller composes it against its
# configured transcriber base URL (e.g. `/api` in dev, `https://...` in
# prod). Leading slash so concatenation with a non-slashed base yields a
# valid path either way.
ROUTE_PREFIX = "/outputs"


# Lossless, modest-size encoding. `PCM_16` is fine because Demucs's wav
# outputs are already int16; we read them as float32 just to do the
# bass+other+vocals sum without integer overflow, then quantise back.
FLAC_SUBTYPE = "PCM_16"


class OutputSink:
    """Writes per-request stem deliverables and tracks their URL paths.

    Construction takes the request's folder name (same convention as
    `DebugSink` — see `debug.mint_request_folder_name`) so an operator can
    correlate `/outputs/<name>/` with `/debug/<name>/`.
    """

    def __init__(self, base_dir: Path, folder_name: str) -> None:
        self.base_dir = base_dir
        self.folder_name = folder_name
        self.dir = base_dir / folder_name
        # NB: the request directory is created lazily on the first
        # successful write (see `_ensure_dir`), not here. An eagerly
        # mkdir'd-but-empty `outputs/<name>/` is indistinguishable from
        # "the pipeline died before producing any deliverable", which is
        # exactly the confusing state we want to avoid: with lazy
        # creation, the folder's mere existence guarantees ≥1 FLAC landed.

    def _ensure_dir(self) -> None:
        self.dir.mkdir(parents=True, exist_ok=True)

    # ----------------------------------------------------------- writes

    def save_flac_from_wav(self, name: str, src: Path) -> Path | None:
        """Re-encode `src` (any libsndfile-readable format) into `<dir>/<name>.flac`.

        Writes happen as soon as the caller has the source on disk (e.g.
        the drum stem the instant `stems_all` finishes, the per-instrument
        stems the instant `stems_per` finishes) — never deferred to the
        end of the request — so the deliverables are downloadable while
        the slow LLM stages are still running.

        Returns the destination path on success, or `None` on failure
        (logged, not raised — a missing deliverable is recoverable from
        the corresponding debug artifact if the operator needs to).
        """
        if not src.exists():
            log.warning("OutputSink: source %s does not exist; skipping %s", src, name)
            return None
        dest = self.dir / f"{name}.flac"
        try:
            self._ensure_dir()
            data, sr = sf.read(str(src), always_2d=True, dtype="float32")
            np.clip(data, -1.0, 1.0, out=data)
            sf.write(str(dest), data, sr, format="FLAC", subtype=FLAC_SUBTYPE)
        except (OSError, RuntimeError, ValueError) as exc:
            log.warning("OutputSink: encoding %s -> %s failed: %s", src, dest, exc)
            return None
        log.info("OutputSink: wrote %s", dest)
        return dest

    def save_mp3_from_wav(self, name: str, src: Path) -> Path | None:
        """Re-encode `src` (any ffmpeg-readable audio) into `<dir>/<name>.mp3`.

        Used by the debug-bundle builder so a 5-stem debug zip stays compact
        enough to email / drop into a chat. ffmpeg is already in the Docker
        image (libsndfile/librosa pull it in), so we shell out instead of
        adding a Python MP3 encoder dep (`lameenc` etc.). Same lazy-dir +
        log-don't-raise contract as the FLAC writer.

        Skips re-encoding when `<dir>/<name>.mp3` already exists and is at
        least as new as `src` — the common resume case, where a prior run
        already produced both the FLAC and its MP3 transcode and neither
        upstream stage re-ran. The MP3 is a deterministic function of the
        FLAC, so timestamp parity is enough; a resume that re-runs
        `stems_all` / `stems_per` overwrites the FLACs in place and bumps
        their mtime past the stale MP3, triggering a fresh encode.
        """
        if not src.exists():
            log.warning("OutputSink: source %s does not exist; skipping %s", src, name)
            return None
        dest = self.dir / f"{name}.mp3"
        if dest.exists():
            try:
                if dest.stat().st_mtime >= src.stat().st_mtime:
                    log.info(
                        "OutputSink: reusing fresh %s (src %s unchanged)",
                        dest, src,
                    )
                    return dest
            except OSError as exc:
                # Stat failure is recoverable — fall through and re-encode.
                log.debug("OutputSink: stat for reuse check failed: %s", exc)
        try:
            self._ensure_dir()
            subprocess.run(
                [
                    "ffmpeg", "-y", "-loglevel", "error",
                    "-i", str(src),
                    "-c:a", "libmp3lame", "-b:a", MP3_BITRATE,
                    str(dest),
                ],
                check=True,
                capture_output=True,
            )
        except (OSError, subprocess.CalledProcessError) as exc:
            stderr = (
                exc.stderr.decode("utf-8", errors="replace")
                if isinstance(exc, subprocess.CalledProcessError) and exc.stderr
                else ""
            )
            log.warning(
                "OutputSink: ffmpeg encoding %s -> %s failed: %s %s",
                src, dest, exc, stderr,
            )
            return None
        log.info("OutputSink: wrote %s", dest)
        return dest

    def save_text(self, name: str, text: str) -> Path | None:
        """Write `text` verbatim to `<dir>/<name>` (name carries its own
        extension, e.g. `final.jot`). Same lazy-dir + log-don't-raise
        contract as `save_flac_from_wav`.
        """
        dest = self.dir / name
        try:
            self._ensure_dir()
            dest.write_text(text, encoding="utf-8")
        except OSError as exc:
            log.warning("OutputSink: writing %s failed: %s", dest, exc)
            return None
        log.info("OutputSink: wrote %s", dest)
        return dest

    def save_bytes(self, filename: str, data: bytes) -> Path | None:
        """Write raw `data` to `<dir>/<filename>` (filename carries its
        own extension, e.g. `prediction.mid`). Same lazy-dir +
        log-don't-raise contract as `save_flac_from_wav`.
        """
        dest = self.dir / filename
        try:
            self._ensure_dir()
            dest.write_bytes(data)
        except OSError as exc:
            log.warning("OutputSink: writing %s failed: %s", dest, exc)
            return None
        log.info("OutputSink: wrote %s", dest)
        return dest

    # -------------------------------------------------------------- read

    def existing_path(self, name: str) -> Path | None:
        """Return `<dir>/<name>.flac` if it already exists on disk."""
        candidate = self.dir / f"{name}.flac"
        return candidate if candidate.is_file() else None

    def existing_file(self, filename: str) -> Path | None:
        """Return `<dir>/<filename>` (extension included) if it exists."""
        candidate = self.dir / filename
        return candidate if candidate.is_file() else None

    def url_for(self, name: str) -> str:
        """URL path (no host) for a stem deliverable by base name."""
        return f"{ROUTE_PREFIX}/{self.folder_name}/{name}.flac"

    def url_for_file(self, filename: str) -> str:
        """URL path (no host) for an artifact whose name already
        carries its extension (e.g. `prediction.mid`)."""
        return f"{ROUTE_PREFIX}/{self.folder_name}/{filename}"


def make_output_sink(folder_name: str, base_dir: Path) -> OutputSink | None:
    """Construct an OutputSink rooted at `base_dir / folder_name`, or
    return `None` if the base directory can't be created.

    Falls back to None rather than raising so a misconfigured volume mount
    degrades to "no URLs in the response" rather than failing the whole
    transcription request. Only the `StaticFiles` root is created here;
    the per-request directory is created lazily on the first successful
    write (see `OutputSink._ensure_dir`).
    """
    try:
        base_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        log.warning("Could not create outputs dir %s: %s", base_dir, exc)
        return None
    return OutputSink(base_dir, folder_name)


def _scavenge_no_drums(folder: Path | None) -> Path | None:
    """Find a previous run's drumless mix under `<folder>/stems_all/`.

    `no_drums` is the one deliverable not carried on `PipelineContext`
    (no stage consumes it), so on a resume that skips `stems_all` it can
    only be recovered from the debug folder the resume is replaying.
    """
    if folder is None:
        return None
    stems_all = folder / "stems_all"
    if not stems_all.is_dir():
        return None
    for child in sorted(stems_all.iterdir()):
        if child.is_file() and child.stem == "no_drums":
            return child
    return None


def materialize_pending(
    output_sink: OutputSink | None,
    *,
    drum_stem: Path | None,
    per_instrument_stems: dict[str, Path],
    final_jot: str | None,
    predicted_midi: bytes | None = None,
    scavenge_dir: Path | None = None,
) -> None:
    """Backfill any deliverable the stage bodies didn't already write.

    The early, in-stage writes (`_do_stems_all` / `_do_stems_per`) only
    fire when those stages actually run. A `/transcribe/resume` that
    starts at `beats` or later skips them entirely, so without this the
    outputs folder would stay empty even though the source stems are
    hydrated into the context straight from the resume folder. This runs
    once after the pipeline and fills the gaps from whatever sources are
    available — no recomputation. Already-present FLACs are left as the
    stage wrote them: a stage that actually ran has already overwritten
    its FLAC in-place via `save_flac_from_wav` (soundfile truncates the
    dest), so the no-op here is correct for non-skipped stages too; a
    skipped stage's FLAC is intentionally kept. `final.jot` is always
    (re)written so it reflects the latest refine result, and
    `prediction.mid` is (re)written whenever `predicted_midi` is present
    — it is set only when the filter-mode transcribe stage actually ran
    this invocation, so a non-skipped transcribe overwrites the stale
    MIDI from a prior run instead of leaving it.
    """
    if output_sink is None:
        return
    if (
        output_sink.existing_path("drum_stem") is None
        and drum_stem is not None
        and drum_stem.exists()
    ):
        output_sink.save_flac_from_wav("drum_stem", drum_stem)
    for pitch, path in per_instrument_stems.items():
        if output_sink.existing_path(f"stem_{pitch}") is None and path.exists():
            output_sink.save_flac_from_wav(f"stem_{pitch}", path)
    if output_sink.existing_path("no_drums") is None:
        scavenged = _scavenge_no_drums(scavenge_dir)
        if scavenged is not None:
            output_sink.save_flac_from_wav("no_drums", scavenged)
    if final_jot:
        output_sink.save_text("final.jot", final_jot)
    if predicted_midi is not None:
        # Unguarded by design: predicted_midi is set only when the
        # filter-mode transcribe stage ran this invocation (it stays
        # None on a resume that skips transcribe), so its presence means
        # the stage was not skipped and any prior prediction.mid is
        # stale and must be overwritten.
        output_sink.save_bytes("prediction.mid", predicted_midi)
